### ISSUE TITLE
Transfer to the jQuery org?

### ISSUE THREAD

**Issue by mgol** [rxaviers/builder-x#2]
@rxaviers This package currently breaks on Node 16 due to outdated dependencies and it's used by jQuery UI in the release process. Could you transfer it to the jQuery org so that I can fix it?

If you don't have relevant permissions then please ping me so that I can give them to you.

This is similar to my past transfer request from https://github.com/jquery/jquery-ui-themeroller/issues/5

The issue in question is:
* https://github.com/archiverjs/node-archiver/issues/491
* https://github.com/nodejs/node/issues/37027

**Comment by rxaviers** [comment]
Hi @mgol , sure! Transferring to jquery.

**Comment by rxaviers** [comment]
Done 😉

**Comment by mgol** [comment]
Thank you! 🙂

**Comment by mgol** [comment]
Oh, can you also add me to the list of package owners?
```
npm owner add mgol node-packager
```
I hope npm will cooperate this time. 😉

**Comment by mgol** [comment]
ping @rxaviers :)

**Comment by rxaviers** [comment]
Thanks for the reminder. Done

**Comment by mgol** [comment]
Thank you!
